import { Playlist } from 'types'

export const playlistMock: Playlist = {
  id: '123',
  name: 'random-fy',
  description:
    'playlist generated by randomfy. Url: https://random-fy.vercel.app/',
  uri: 'random-fy.uri'
}
