name: Coverage

on:
  pull_request:
    branches: [main]

jobs:
  coverage:
    name: Get Coverage

    permissions:
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
